feat: Add pricing calculator
pluralsh/design-system pull request #433
Opened 2023-03-09 16:02 UTC by maciaszczykm

Design: https://www.figma.com/file/vw6W6kaN658dkOAl74l3Hg/Pricing-Calculator?node-id=1-2&t=m5oeFv7TNUU3CdaD-0

2023-03-15 14:39 UTC, swoodward90 commented
@maciaszczykm we need to see how the meeting goes today, but I'm fairly certain we'll be implementing a cap on the number of users that an account can have on the free plan (see https://github.com/pluralsh/plural/pull/1007)
In that case, we'll need to adjust the extended slider to automatically flip to the Professional plan when > 5 users are selected and probably have an info callout on the users number the same way we do for Cloud Costs

2023-03-16 13:57 UTC, floreks approved these changes

2023-03-16 17:56 UTC, dogmar requested changes

2023-03-16 17:56 UTC, dogmar commented on src/components/pricingcalculator/controls/UsersControl.tsx
> +      caption="Plural is free for up to 5 open-source users. Account requiring more than 5 users and accounts on the professional plan will add $49/user."
```suggestion
      caption="Plural is free for up to 5 open-source users. Accounts requiring more than 5 users and accounts on the professional plan will add $49/user."
```

2023-03-16 17:56 UTC, dogmar commented
Looks good. Just caught one typo in some caption text.

2023-03-17 08:20 UTC, maciaszczykm commented
@dogmar Fixed, PTAL.

2023-03-20 07:50 UTC, merged